Fix linter errors reported by golangci-lint
Fixes the following linter errors:
pkg/config/config.go:30:20: error strings should not be capitalized or end with punctuation or a newline (golint)

cmd/compserv-server.go:16: File is not `gofumpt`-ed (gofumpt)

cmd/compserv-server.go:16: line is 125 characters (lll)

cmd/compserv-server.go:37:18: Error return value of `grpcServer.Serve` is not checked (errcheck)
        grpcServer.Serve(lis)
                        ^
pkg/config/config.go:70:2: commentFormatting: put a space between `//` and comment text (gocritic)
        //Create a Secrets Manager client
        ^

pkg/config/config.go:27:2: don't use underscores in Go names; var `db_host` should be `dbHost` (golint)
        db_host := viper.GetString("database.host")
        ^
pkg/config/config.go:28:2: don't use underscores in Go names; var `db_port` should be `dbPort` (golint)
        db_port := viper.GetString("database.port")
        ^
pkg/config/config.go:29:2: don't use underscores in Go names; var `db_username` should be `dbUsername` (golint)
        db_username := viper.GetString("database.username")
        ^
pkg/config/config.go:30:2: don't use underscores in Go names; var `db_name` should be `dbName` (golint)
        db_name := viper.GetString("database.name")
        ^
pkg/config/config.go:31:2: don't use underscores in Go names; var `db_secret_arn` should be `dbSecretArn` (golint)
        db_secret_arn := viper.GetString("database.secret_arn")
        ^
pkg/config/config.go:32:2: don't use underscores in Go names; var `db_secret_region` should be `dbSecretRegion` (golint)
        db_secret_region := viper.GetString("database.secret_region")
        ^
pkg/config/config.go:33:2: don't use underscores in Go names; var `app_host` should be `appHost` (golint)
        app_host := viper.GetString("app.host")
        ^
pkg/config/config.go:34:2: don't use underscores in Go names; var `app_port` should be `appPort` (golint)
        app_port := viper.GetString("app.port")
        ^

pkg/config/config.go:29:2: variable 'err' is only used in the
if-statement (pkg/config/config.go:30:2); consider using short syntax
    (ifshort)
            err := viper.ReadInConfig()
                    ^

Suppresses the following warnings:
pkg/config/config.go:41:2: ifElseChain: rewrite if-else to switch statement (gocritic)

pkg/api/server.go:10:29: exported func NewServer returns unexported type *github.com/rhmdnd/compserv/pkg/api.server, which can be annoying to use (golint)

pkg/config/config.go:132:9: indent-error-flow: if block ends with a return statement, so drop this else and outdent its block (revive)

pkg/config/config.go:132:9: indent-error-flow: if block ends with a return statement, so drop this else and outdent its block (revive)
        } else {
                decodedBinarySecretBytes := make([]byte, base64.StdEncoding.DecodedLen(len(result.SecretBinary)))
                secretLen, err := base64.StdEncoding.Decode(decodedBinarySecretBytes, result.SecretBinary)
                if err != nil {
                        fmt.Println("Base64 Decode Error:", err)
                        return secretString
                }
                decodedBinarySecret = string(decodedBinarySecretBytes[:secretLen])
                return decodedBinarySecret
        }